apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "fluentd"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fluentd.name" . }}
        component: "fluentd"
        release: {{ .Release.Name | quote }}
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluentd
        image: {{ .Values.image | quote }}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "{{ .Values.elasticsearch.host | default (include "elasticsearch.service.fullname" .) }}"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "{{ .Values.elasticsearch.port }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        command: # TODO: add  fluent-plugin-concat to Dockerfile
          - "sh"
          - "-c"
          - > 
            exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT ;

#            apk add --no-cache --virtual .build-deps build-base ruby-dev libffi-dev ;
#            gem install fluent-plugin-concat ;
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # - name: varlibdockercontainersexternal
        #   mountPath: /mnt/storage/docker_lib
        #   readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: {{ template "fluentd.configmap.fullname" . }}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # - name: varlibdockercontainersexternal
      #   hostPath:
      #     path: /mnt/storage/docker_lib
