apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "elasticsearch.client.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "elasticsearch"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: {{ template "elasticsearch.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      component: "elasticsearch"
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      role: client
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        component: "elasticsearch"
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        role: client
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: {{ default .Values.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}
          securityContext:
            privileged: true
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
      containers:
      - name: es-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: {{ .Values.image | quote }}
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: {{ .Values.clusterName | quote }}
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1024m -Xmx1024m"
        - name: "DISCOVERY_SERVICE"
          value: "{{ template "elasticsearch.discovery.fullname" . }}"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
