kind: Service
apiVersion: v1
metadata:
  name: {{ template "openvpn.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openvpn.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: openvpn
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: {{ .Values.openvpn.OVPN_PROTO | upper }}
    {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ template "openvpn.fullname" . }}
  type: {{ .Values.service.type }}
