{{- if .Values.pki_in_secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openvpn.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openvpn.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  server_key: {{ (.Files.Get .Values.pki_in_secret.server_key) | b64enc | quote }}
  server_cert: {{ (.Files.Get .Values.pki_in_secret.server_cert) | b64enc | quote }}
  ca: {{ (.Files.Get .Values.pki_in_secret.ca) | b64enc | quote }}
  dh: {{ (.Files.Get .Values.pki_in_secret.dh) | b64enc | quote }}
  serial: {{ (.Files.Get .Values.pki_in_secret.serial) | b64enc | quote }}
  index: {{ (.Files.Get .Values.pki_in_secret.index) | b64enc | quote }}
  ca_key: {{ (.Files.Get .Values.pki_in_secret.ca_key) | b64enc | quote }}
{{- end -}}
