apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "carbonapi.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "carbonapi.server.fullname" . }}-config
data:
{{ toYaml .Values.configs | indent 2 }}
