apiVersion: v1
kind: Service
metadata:
{{- if .Values.server.service.annotations }}
  annotations:
{{ toYaml .Values.server.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "carbonapi.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "carbonapi.server.fullname" . }}
spec:
  ports:
    - name: carbonapi
      port: 8081
  selector:
    app: {{ template "carbonapi.fullname" . }}
    component: "{{ .Values.server.name }}"
  type: "{{ .Values.server.service.type }}"
