apiVersion: v1
kind: Service
metadata:
{{- if .Values.server.service.annotations }}
  annotations:
{{ toYaml .Values.server.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "go-carbon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "go-carbon.server.fullname" . }}
spec:
  ports:
    - name: carbonreceiverplaintext
      port: 2003
    - name: carbonreceiverpickle  
      port: 2004
    - name: carbon
      port: 8080
  selector:
    app: {{ template "go-carbon.fullname" . }}
    component: "{{ .Values.server.name }}"
  type: "{{ .Values.server.service.type }}"
